version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/java:17
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity

  mysql:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
